import './globals.css'
import { Inter } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.min.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Muzaffar',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
      </head>
      <body className={`root_div ${inter.className}`}>{children}</body>
    </html>
  )
}
